### ISSUE TITLE
type check is broken 

### ISSUE THREAD

**Issue by podhmo** [podhmo/with-help#4]
```ts
import { parseArgs } from "jsr:@podhmo/with-help"

const args = parseArgs(Deno.args, {
    string: ["name"],
    boolean: ["color"],
} as const)

const _: never = args;
console.log(`hello ${args.name}`)
```

```console
$ deno check hello.ts
Check file:///home/po/ghq/github.com/podhmo/with-help/_examples/hello.ts
error: TS2322 [ERROR]: Type '"color"' is not assignable to type '"help"'.
    boolean: ["color"],
              ~~~~~~~
    at file:///home/po/ghq/github.com/podhmo/with-help/_examples/hello.ts:5:15

TS2322 [ERROR]: Type 'Parsed<"name", string, string, string, string>' is not assignable to type 'never'.
const _: never = args;
      ^
    at file:///home/po/ghq/github.com/podhmo/with-help/_examples/hello.ts:8:7
```

**Comment by podhmo** [comment]
hmm 
![{0EF3411C-A2A3-4B29-8F10-8E743B24E4CA}](https://github.com/user-attachments/assets/afd91719-4284-465b-93e6-93ea050bdfe3)

**Comment by podhmo** [comment]
with negatable option, the boolean option's type  is not widen.

```ts
const args = parseArgs(Deno.args, {
    string: ["name"],
    boolean: ["color"],
    negatable: ["color"],
} as const)
```

**Comment by podhmo** [comment]
fixed if

```diff
diff --git a/parse-args.ts b/parse-args.ts
index fb7a7b8..a007ff1 100644
--- a/parse-args.ts
+++ b/parse-args.ts
@@ -72,7 +72,7 @@ export function parseArgs<
   args: string[],
   options: {
     // original options
-    boolean?: (EnsureLiteralArray<BooleanKeys>[number] | "help")[];
+    boolean?: EnsureLiteralArray<BooleanKeys>;
     string?: EnsureLiteralArray<StringKeys>;
     collect?: EnsureLiteralArray<CollectKeys>[number] extends StringKeys[number]
       ? CollectKeys
```

**Comment by podhmo** [comment]
but collectable is widen. so  the type of `args.name` is `string[]`

**Comment by podhmo** [comment]
OK, we need tests
